- .github/workflows/eslint.yml
- Linter が落ちてないかを確認する CI の作成
- Linter が落ちている場合に自動で修正する機能
→ 自動で修正のコマンドを走らせても deploy で落ちたからあまり意味がなかった
→ 運用としては、ローカルで修正して deploy が落ちないようにする 
- close #3
- #3
> Linter が落ちてないかを確認する CI の作成

- .vscode/settings.json
- 改行コードを `settings.json` を明示的に指定した
1.  [このリンク](https://yu-report.com/entry/gitcrlf/) を参考に、`git config --global core.autocrlf false` をターミナルで実行する
2. このレポジトリを clone し直して、VSCode のデフォルトが LF になり、特段エラーが出なくなる 
- close #27
- #27
> 改行コード周りの修正

- .github/semantic.yml
- `semantic.yml` に `allowMergeCommits: true` を追加することで、'Merge branch "master" into fix/delete-all-tests' のようなコミットメッセージでも CI が通るようになる
⚠ `semantic.yml` の設定は default のブランチに Merge されないと、反映されないためこの時点で動作確認をすることができないため、お、こいつ CI の設定うまくいく方法見つけたんだな、やるなという気持ちだけ思ってもらって、脳死で Approve してもらって良いです
別レポジトリでこの設定を追加すればうまくいくことを確認済みです
信じてください
- close #32
- #32
> Semantic PRs のカスタム設定

- pages/index.tsx
- pages/start-game.tsx
- ホーム画面からゲーム参加画面への遷移
- 画面の遷移以外のこと (style etc…)
- close #30
- #30
> ホーム画面からゲーム参加画面への遷移

- package-lock.json
- package.json
- pages/components.tsx
- src/components/CustomInput.tsx
- src/components/DeleteHintList.tsx
- yarn.lock
- ヒントにチェックを押すと削除するヒントの状態が保存されるように設定
- 自動化
- close #23 
- #23
> feat:ヒントを削除するコンポーネント

- pages/components.tsx
- src/components/CustomTitleText.tsx
- src/components/WordOut.tsx
- コンポーネント作成
- xxx
- close #33 
- #0
> タイトル+色で囲われたコンポーネント作成

- pages/_app.tsx
- pages/components.tsx
- pages/start-game.tsx
- src/components/PageBackIcon.tsx
- yarn.lock
- ルーム作成or参加のUIを作成
- UIの完成度、(色、正確な位置などなど)
- close #36 
- #36
> feat: 作成or参加のUIを作成

- pages/join-room.tsx
- ルーム参加画面の組み上げ
- xxx
- close #38 
- #0
> feat: ルーム参加画面のUI

- pages/create-room.tsx
- ルーム作成のためのUIの作成
- xxx
- close #37 
- #37
> feat: ルーム作成のためのUIの作成

- pages/components.tsx
- src/components/game/ThinkingTheme.tsx
- 話し合い画面のコンポーネント作成
- xxx
- close #52 
- #52
> feat: 話し合い画面のコンポーネント作成

- pages/components.tsx
- src/components/common/CustomTitleText.tsx
- src/components/game/JudgeAnswer.tsx
- 回答が正解かを判定する画面の実装
- 正解が押された場合には、コンソールに `true` が表示される
- 不正解が押された場合には、コンソールに `false` が表示される
- close #58
- #58
> 回答が正解かを判定する画面の実装

- pages/answer.tsx
- pages/components.tsx
- src/components/common/CustomInput.tsx
- src/components/game/answer.tsx
- 一旦画面を作成しました。
- ヒントを渡す部分と画面遷移はまだ終わっていない
- close #57 
- #57
> feat: 一旦画面を作成しました。(ヒントを渡す部分と画面遷移はまだ終わっていない)

- pages/components.tsx
- src/components/game/InputTheme.tsx
- お題入力画面の作成
- xxx
- close #53 
- #0
> feat: お題入力画面

- pages/components.tsx
- src/components/game/DiscussJudgeAns.tsx
- 回答が正解かを話し合う画面を作成
- 関数名は長かったのでDiscussJudgeAnsにしました
- xxx
- close #59 
- #0
> feat: 回答の判定話し合い待機画面

- .eslintrc.json
- package.json
- pages/_app.tsx
- pages/create-room.tsx
- pages/http-error.tsx
- pages/wait.tsx
- src/components/game/HowToDecideTheme.tsx
- src/data/BaseUrl.tsx
- src/store/Recoil.tsx
- tsconfig.json
- yarn.lock
- ユーザの追加時に DB にデータを追加
- Recoil を追加 (グローバルに値を使用するため)
- Http Request エラー時のページの作成
- 正常な場合 `/wait` に Id が表示される
- エラー吐いたら `/http-error` に遷移する
- close #79
- #79
> ユーザの追加時に DB にデータを追加

- .vscode/settings.json
- pages/create-room.tsx
- pages/wait.tsx
- src/data/BaseUrl.tsx
- src/store/Recoil.tsx
- 部屋の作成時に DB に値を追加
- close #78
- #78
> 部屋の作成時に DB に値を追加

- pages/join-room.tsx
- ルーム参加時にユーザを DB に登録するまでの実装
- close #84
- #84
> ルーム参加時にユーザを DB に登録するまでの実装

- pages/components.tsx
- pages/wait.tsx
- src/components/MemberList.tsx
-  MemberListにアイコンを追加する
- xxx
- close #76 
- #76
> fix: MemberListにアイコンを追加する

- pages/components.tsx
- pages/wait.tsx
- src/components/MemberList.tsx
- 参加者のリストを API から取得
- close #87
- #87
> 参加者のリストを API から取得

- pages/create-room.tsx
- pages/game.tsx
- pages/join-room.tsx
- pages/wait.tsx
- src/hooks/useError.tsx
- tsconfig.json
- ルーム作成者がゲームを開始
- xxx
- close #86
- #86
> ルーム作成者がゲームを開始

- pages/components.tsx
- src/components/game/Result.tsx
- リザルト画面のコンポーネント作成
- xxx
- close #0
- #0
> feat: リザルト画面

- pages/components.tsx
- pages/game.tsx
- src/components/game/Answer.tsx
- 回答者が回答を入力する際のヒントを DB から取得してきたものに置き換え
- xxx
- close #95
- #95
> 回答者が回答を入力する際のヒントを DB から取得してきたものに置き換え

- src/data/AvatarList.tsx
- アイコン
- xxx
- close #96 
- #0
> style: アイコン

- pages/wait.tsx
- ルーム参加者がゲーム開始時に適切な画面へ遷移するように変更
- xxx
- close #93 
- #93
> feat: ルーム参加者がゲーム開始時に適切な画面へ遷移するように変更

- pages/components.tsx
- pages/game.tsx
- pages/wait.tsx
- src/components/game/Answer.tsx
- src/components/game/Wait.tsx
- 回答者が step6->7 に遷移
- xxx
- close #98
- #98
> 回答者が step6->7 に遷移

- pages/wait.tsx
- 参加者の時に待機ルームで戻るボタンを押すとメインルームに戻るように修正
- xxx
- close #103 
- #103
> fix: 戻るボタンの画面遷移修正

- pages/components.tsx
- pages/game.tsx
- src/components/game/HowToDecideTheme.tsx
- role2 の人がお題の決定方法を API で送信して、適切な画面へ遷移するようにした
- その後の画面のUIの詳細
- close #107
- #107
> feat: role2 の人がお題の決定方法を API で送信して、適切な画面へ遷移するようにした

- pages/components.tsx
- pages/game.tsx
- src/components/game/DiscussJudgeAns.tsx
- src/components/game/Result.tsx
- role1|3：ste6 -> 7
- xxx
- close #116
- #0
> role1|3：ste6 -> 7

- pages/components.tsx
- pages/game.tsx
- src/components/game/InputTheme.tsx
- step2～step3への遷移
- xxx
- close #108 
- #108
> feat: step2～step3への遷移

- pages/start-game.tsx
- ボタンの色とか(まだ変えるかも)
- xxx
- close #123 
- #0
> style 諸々調整

- pages/components.tsx
- pages/game.tsx
- src/components/game/InputHint.tsx
- step3～step4への画面の遷移
- xxx
- close #109 
- #109
> feat: step3～step4への画面の遷移

- pages/components.tsx
- src/components/game/AnswerWait.tsx
- ゲッサーが回答しているときのヒントホルダー待機画面
- xxx
- close #121 
- #0
> feat: ゲッサー回答中のヒントホルダーの待機画面

- pages/components.tsx
- pages/game.tsx
- src/components/game/JudgeAnswer.tsx
- role2のステップ6～ステップ7への遷移
- xxx
- close #115 
- #115
> feat: role2のステップ6～ステップ7への遷移

- pages/components.tsx
- pages/game.tsx
- src/components/game/AnswerWait.tsx
- role2と3のステップ5～6への遷移
- xxx
- close #113 
- close #114 
- #113 
- #114
> feat: role2と3のステップ5～6への遷移

- .eslintrc.json
- pages/components.tsx
- pages/create-room.tsx
- pages/game.tsx
- pages/wait.tsx
- src/components/DeleteHintList.tsx
- src/components/game/Answer.tsx
- src/components/game/AnswerWait.tsx
- src/components/game/DeleteHintOtherMasterUI.tsx
- src/components/game/HowToDecideTheme.tsx
- src/components/game/SelectDuplicateHint.tsx
- src/types/type.ts
- tsconfig.json
- role2：step 4 ->5
- ヒントの型の共通化
- 簡単なリファクタリング
- xxx
- close #111
- #111
> role2：step 4 ->5

- pages/create-room.tsx
- pages/join-room.tsx
- src/components/common/NNAndIcon.tsx
- 画面の表示
- xxx
- close #128 
- #0
> style: ルーム参加＆作成画面

- pages/index.tsx
- index.tsx内の修正
- xxx
- close #100 
- #0
> style: index.tsxの修正

- src/components/common/CustomTitleText.tsx
- src/components/common/Respondent.tsx
- src/components/game/Answer.tsx
- src/components/game/AnswerWait.tsx
- src/components/game/DeleteHintOtherMasterUI.tsx
- src/components/game/DiscussJudgeAns.tsx
- src/components/game/HowToDecideTheme.tsx
- src/components/game/InputHint.tsx
- src/components/game/InputTheme.tsx
- src/components/game/JudgeAnswer.tsx
- src/components/game/Result.tsx
- src/components/game/SelectDuplicateHint.tsx
- src/components/game/ThinkingTheme.tsx
- いったんこんなかんじで
- xxx
- close #0
- #0
> style: 一段階目

- pages/components.tsx
- src/components/common/YouAre.tsx
- 自分が人間か人狼かを表すコンポーネントの作成
- ボタンの遷移
- close #144 
- #144
> feat: 自分が人間か人狼かを表すコンポーネントの作成

- pages/create-room.tsx
- 人狼モードを選択できるチェックボックスをルーム作成画面に追加
- xxx
- close #146 
- #0
> feat: 人狼モードの選択ボタンを追加

- pages/components.tsx
- src/components/ChoiceWolfList.tsx
- src/components/game/ChoiceWolf.tsx
- src/types/choice.ts
- 人狼が誰かを選ぶUIの作成
- xxx
- close #150 
- #150
> feat: 人狼が誰かを選ぶUIの作成

- pages/components.tsx
- src/components/common/YouAre.tsx
- 人狼と村人のアイコンを追加
- xxx
- close #149 
- #0
> feat: 人狼と村人のアイコン

- pages/components.tsx
- src/components/game/BanishPerson.tsx
- 追放されるプレイヤーの表示を行う画面を作成
- xxx
- close #156 
- #156
> feat: 追放されるプレイヤーの表示を行う画面を作成

- pages/components.tsx
- src/components/game/PointList.tsx
- src/components/game/Score.tsx
- スコア画面の作成
- xxx
- close #154 
- #0
> feat: スコア画面

- pages/components.tsx
- pages/wolf-wait.tsx
- src/components/game/PointList.tsx
- src/components/game/Score.tsx
- wolf-wait画面の作成
- 画面遷移
- close #167
- #167
> feat: wolf-wait画面の作成

- src/components/game/Wait.tsx
- GIFくっつけただけとも言える
- xxx
- close #164 
- #0
> style: Wait

- pages/join-room.tsx
- join-roomでモードによってgameとwolf-gameどちらかに分岐できるように
- xxx
- close #166 
- #166
> feat: join-roomでモードによってgameとwolf-gameどちらかに分岐できるように

- pages/create-room.tsx
- `GET create-room` の API の仕様変更
- `key` を `wolfMode: bool` に変更
- xxx
- close #176
- #176
> `GET create-room` の API の仕様変更

- pages/components.tsx
- pages/create-room.tsx
- pages/wolf-game.tsx
- pages/wolf-wait.tsx
- src/components/common/YouAre.tsx
- src/components/game/PointList.tsx
- wolf-game.tsxの作成
- xxx
- close #171 
- #0
> feat: wolf-game.tsxの作成

- pages/index.tsx
- 文面＆/のボタン
- xxx
- close #0
- #0
> fix: 文面調整、/のボタンを調整

- pages/game.tsx
- pages/wolf-game.tsx
- src/components/game/Result.tsx
- テーマと回答を取得するタイミングの修正
- step が一気に先に進んでも耐えるようにした
コードを見たら恐らくそういうことかとなるため、動作確認は必要ない
- close #186
- #186
> テーマと回答を取得するタイミングの修正

- pages/wolf-game.tsx
- pages/wolf-wait.tsx
- 人か人狼かの表示を行う
- xxx
- close #183 
- #0
> feat: 人か人狼かの表示を行う

- pages/components.tsx
- pages/wolf-game.tsx
- src/components/ChoiceWolfList.tsx
- src/components/game/Wait.tsx
- src/components/game/wolf/ChoiceWolf.tsx
- src/components/game/wolf/ThemeResult.tsx
- src/types/choice.ts
- src/types/type.ts
- step7～step8の遷移(人狼モード)
- xxx
- close #182 
- #182
> feat: step7～step8の遷移(人狼モード)の追加

- pages/components.tsx
- pages/wolf-game.tsx
- src/components/ChoiceWolfList.tsx
- src/components/game/DeleteHintOtherMasterUI.tsx
- src/components/game/Score.tsx
- src/components/game/VoteResult.tsx
- src/components/game/wolf/BanishPerson.tsx
- src/components/game/wolf/ChoiceWolf.tsx
- xxx
- xxx
- close #194
- close #195
- #0
> 人狼のとこまでいけた

- src/components/game/Answer.tsx
- src/components/game/VoteResult.tsx
- src/components/game/wolf/ChoiceWolf.tsx
- 細やかな処理の修正
- 
- xxx
- close #198 
- #0
> fix: 細やかな処理の修正

- src/data/data.ts
Reverts hacku-chamomilla/doutankyohi-front-end#191
> Revert "デプロイ用 (あとで Revert する)"

- pages/game.tsx
- pages/wolf-game.tsx
- `GET get-role` の params に roomId を追加
- `GET get-role-wolf` の params に roomId を追加
- close #215
- #215
> GET get_role 周りに roomId の引数の追加

- src/data/data.ts
- BE のデプロイのリンクを変更
- dev 環境では localhost を参照して、それ以外では本番環境を参照できるようにした
- close #217
- #217
> BE のデプロイのリンクを変更
